cambios

diff --git a/.github/workflows/docker-scout.yml b/.github/workflows/docker-scout.yml
--- a/.github/workflows/docker-scout.yml
+++ b/.github/workflows/docker-scout.yml
@@ -1,4 +1,4 @@
-name: CI Docker Scout Scan Vulnerable Image
+name: CI Docker Scout Scan
 
 on:
   push:
@@ -19,16 +19,16 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Pull vulnerable test image
-        run: docker pull vulnerables/web-dvwa
+      - name: Pull Docker image
+        run: docker pull mjtaehyung/proyecto:latest
 
       - name: Download Docker Scout CLI
         run: |
           curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin
 
-      - name: Scan vulnerable image with Docker Scout
+      - name: Scan image with Docker Scout
         run: |
-          docker scout cves vulnerables/web-dvwa --format markdown > reporte.md || echo "Scan failed"
+          docker scout cves mjtaehyung/proyecto:latest > reporte.md || echo "Scan failed"
 
       - name: Check if vulnerabilities exist and show message
         run: |
